export const WIN_SUGGESTIONS = {
    Physical: [
        "Wake before 7 AM", "Drink warm water after waking", "Do 10 Surya Namaskar", "Walk 5000+ steps", "Stretch for 5 minutes",
        "Eat a home-cooked breakfast", "Add fruits to breakfast", "Eat dal in one meal", "Eat green vegetables", "Reduce fried snacks",
        "Skip sugary chai once", "Drink 2–3L water", "Take stairs instead of lift", "Walk to nearby shop", "Do 20 push-ups",
        "Do 30 squats", "Do plank for 1 minute", "Do breathing exercises", "Practice pranayama", "Sit with straight posture",
        "Reduce screen time before bed", "Sleep before 11 PM", "Eat dinner before 9 PM", "Eat less salt", "Carry water bottle outside",
        "Avoid packaged junk food", "Eat curd or yogurt", "Eat seasonal fruit", "Walk after dinner", "Do yoga for 10 minutes",
        "Avoid soft drinks", "Take sunlight for 10 minutes", "Stand up every hour", "Use standing desk for a while", "Limit tea to 2 cups",
        "Avoid smoking", "Avoid alcohol for the day", "Do neck stretches", "Do eye relaxation exercises", "Wash fruits before eating",
        "Cook one healthy meal", "Eat nuts (almonds/peanuts)", "Avoid late night snacks", "Eat whole grains (roti/brown rice)", "Avoid overeating",
        "Drink lemon water", "Eat homemade snacks", "Use less oil in cooking", "Practice deep breathing", "Walk while talking on phone",
        "Clean your room", "Wash hands frequently", "Sit cross-legged for flexibility", "Use ergonomic chair", "Take a quick power nap",
        "Do mobility exercises", "Do ankle rotations", "Do shoulder rotations", "Maintain personal hygiene", "Brush teeth twice",
        "Take a proper shower", "Use sunscreen if outside", "Stretch hamstrings", "Stretch back", "Walk during lunch break",
        "Eat sprouts", "Drink coconut water", "Avoid excess sugar", "Track daily steps", "Cycle for 10 minutes",
        "Play a sport", "Avoid sitting long hours", "Do breathing before sleep", "Reduce late caffeine", "Carry healthy snacks",
        "Eat homemade lunch", "Practice balance exercise", "Drink buttermilk", "Avoid processed food", "Reduce screen brightness at night",
        "Relax body before sleep", "Sleep in dark room", "Avoid heavy dinner", "Stretch calves", "Practice slow eating",
        "Sit on floor occasionally", "Drink herbal tea", "Eat fiber rich food", "Avoid skipping meals", "Wash vegetables properly",
        "Practice mindful eating", "Reduce junk delivery apps", "Stay hydrated during travel", "Keep good posture while coding", "Do 5 minute meditation",
        "Eat protein source (eggs/paneer)", "Maintain consistent sleep time", "Take short walking breaks", "Avoid excessive mobile usage", "End day with light stretching"
    ],
    Mental: [
        "Write top 3 priorities", "Plan the day", "Read 10 pages of a book", "Learn a new concept", "Solve one problem",
        "Practice coding", "Listen to educational podcast", "Write journal entry", "Reflect on mistakes", "Reduce multitasking",
        "Practice focus for 30 minutes", "Use Pomodoro method", "Limit social media", "Turn off unnecessary notifications", "Learn one new word",
        "Read a news summary", "Solve puzzle or sudoku", "Watch educational video", "Practice memory exercise", "Think about long term goals",
        "Write ideas", "Practice gratitude", "Review weekly goals", "Practice positive thinking", "Practice mindfulness",
        "Reduce negative news consumption", "Read biography", "Improve typing speed", "Learn keyboard shortcuts", "Organize notes",
        "Review yesterday’s work", "Learn new software feature", "Improve English communication", "Read about Indian history", "Study personal finance",
        "Practice logical thinking", "Write thoughts clearly", "Reflect on decisions", "Reduce mental clutter", "Spend 10 minutes in silence",
        "Write long term vision", "Learn from mistakes", "Review achievements", "Practice patience", "Learn productivity method",
        "Listen carefully in conversations", "Practice concentration", "Read technical documentation", "Practice mental math", "Improve problem solving",
        "Practice critical thinking", "Avoid gossip", "Avoid negative thinking", "Learn something practical", "Learn new technology concept",
        "Review career goals", "Study industry trends", "Write daily summary", "Practice creativity", "Brainstorm ideas",
        "Reduce overthinking", "Ask better questions", "Learn from mentors", "Watch educational lecture", "Practice decision making",
        "Learn new framework concept", "Break complex problems", "Organize digital files", "Improve reading speed", "Write blog idea",
        "Document learning", "Practice structured thinking", "Improve presentation skills", "Learn negotiation basics", "Practice curiosity",
        "Learn Indian economy basics", "Read long form article", "Evaluate personal habits", "Track learning progress", "Review daily mistakes",
        "Write solutions", "Practice calm thinking", "Improve planning ability", "Reflect before reacting", "Learn something outside tech",
        "Practice discipline", "Build knowledge map", "Write summary of book", "Reduce information overload", "Focus on one task",
        "Practice mental clarity", "Write weekly ideas", "Build thinking framework", "Evaluate priorities", "Improve logical reasoning",
        "Practice strategic thinking", "Reduce mental distractions", "Read research article", "Improve curiosity", "End day with reflection"
    ],
    Social: [
        "Greet family in morning", "Call parents", "Help someone at home", "Have dinner with family", "Ask someone about their day",
        "Appreciate a colleague", "Smile at people", "Listen without interrupting", "Avoid arguments", "Respect elders",
        "Thank someone", "Encourage a friend", "Send supportive message", "Check on a friend", "Help coworker",
        "Share useful information", "Attend family event", "Help neighbor", "Be patient in queues", "Speak politely",
        "Avoid gossip", "Resolve small conflict", "Offer help voluntarily", "Appreciate good work", "Celebrate others success",
        "Build professional network", "Reply to messages", "Keep commitments", "Be punctual", "Share food",
        "Offer seat to elders", "Respect domestic workers", "Tip fairly", "Volunteer help", "Teach someone something",
        "Encourage junior colleague", "Mentor someone", "Support small business", "Participate in team discussions", "Maintain eye contact",
        "Respect different opinions", "Avoid rude language", "Thank service staff", "Support local vendors", "Celebrate festivals together",
        "Maintain friendships", "Send birthday wishes", "Respect cultural diversity", "Practice empathy", "Listen actively",
        "Encourage team members", "Offer constructive feedback", "Support community", "Avoid negative talk", "Share opportunities",
        "Appreciate family efforts", "Spend quality time", "Ask meaningful questions", "Be honest", "Help someone struggling",
        "Be respectful online", "Support colleague growth", "Help children learn", "Show kindness daily", "Build trust",
        "Respect personal boundaries", "Appreciate teachers", "Attend social gatherings", "Connect with old friends", "Support community causes",
        "Donate clothes", "Share knowledge", "Offer guidance", "Encourage healthy habits", "Participate in celebrations",
        "Respect religious practices", "Avoid toxic conversations", "Apologize when wrong", "Practice gratitude socially", "Invite someone for tea",
        "Encourage collaboration", "Share positive news", "Support mental health", "Avoid online arguments", "Appreciate effort",
        "Encourage family bonding", "Help someone find job", "Share career advice", "Be dependable", "Respect public spaces",
        "Promote kindness", "Support community cleanliness", "Participate in volunteering", "Show compassion", "Respect different lifestyles",
        "Be patient with children", "Be kind to animals", "Maintain relationships", "Build trust daily", "End day with gratitude for people"
    ],
    Financial: [
        "Track daily spending", "Avoid impulse buying", "Cook at home", "Carry lunch to office", "Use UPI wisely",
        "Save small amount daily", "Review bank balance", "Avoid unnecessary subscriptions", "Pay credit card bill on time", "Compare prices before buying",
        "Use public transport", "Avoid food delivery apps", "Buy local produce", "Use cashback offers wisely", "Set daily spending limit",
        "Review monthly budget", "Save coins/loose change", "Invest small amount", "Learn about mutual funds", "Avoid EMI purchases",
        "Reduce electricity usage", "Turn off unused appliances", "Plan grocery shopping", "Avoid brand obsession", "Repair instead of replacing",
        "Track UPI history", "Save for emergency fund", "Avoid unnecessary upgrades", "Use discount days wisely", "Reuse household items",
        "Buy in bulk if cheaper", "Plan travel expenses", "Reduce petrol usage", "Maintain vehicle properly", "Review SIP investments",
        "Avoid gambling", "Avoid risky trading", "Learn taxation basics", "File taxes on time", "Save receipts",
        "Use budgeting app", "Invest in skill development", "Reduce online shopping", "Buy durable goods", "Avoid luxury spending",
        "Pay bills on time", "Reduce electricity waste", "Monitor bank SMS alerts", "Review subscriptions", "Build savings habit",
        "Track monthly expenses", "Avoid payday loans", "Compare insurance plans", "Maintain emergency cash", "Save salary percentage",
        "Increase financial literacy", "Read finance books", "Plan long term investments", "Diversify investments", "Avoid financial scams",
        "Verify unknown calls", "Maintain credit score", "Use debit card responsibly", "Review insurance coverage", "Plan retirement savings",
        "Avoid lifestyle inflation", "Save bonus money", "Invest tax savings", "Track net worth", "Plan big purchases",
        "Reduce dining out", "Learn about inflation", "Build passive income ideas", "Increase income skills", "Review career growth",
        "Negotiate salary when possible", "Learn freelancing opportunities", "Save festival expenses", "Plan yearly budget", "Avoid unnecessary loans",
        "Pay debts early", "Maintain financial discipline", "Teach family finance basics", "Invest in education", "Plan insurance needs",
        "Avoid pyramid schemes", "Track financial goals", "Monitor investment performance", "Automate savings", "Maintain bank records",
        "Check credit report", "Plan children education fund", "Keep emergency contacts", "Maintain documentation", "Avoid risky shortcuts",
        "Learn budgeting methods", "Improve earning capacity", "Maintain financial awareness", "Reduce wasteful spending", "End day within budget"
    ],
    Spiritual: [
        "Wake with gratitude", "Pray in morning", "Light diya", "Visit temple", "Chant mantra",
        "Read Bhagavad Gita verse", "Practice meditation", "Sit quietly for 5 minutes", "Practice mindfulness", "Reflect on actions",
        "Practice kindness", "Forgive someone", "Avoid anger", "Help needy person", "Donate small amount",
        "Feed animals", "Respect all religions", "Practice patience", "Practice humility", "Express gratitude",
        "Do deep breathing", "Spend time in nature", "Observe silence", "Reflect on purpose", "Practice compassion",
        "Help strangers", "Practice generosity", "Avoid harsh words", "Practice truthfulness", "Control ego",
        "Maintain inner calm", "Avoid jealousy", "Appreciate life", "Accept challenges calmly", "Practice self control",
        "Reflect on karma", "Practice positive thinking", "Pray for others", "Be mindful of actions", "Practice detachment",
        "Focus on present moment", "Avoid greed", "Reflect on life lessons", "Maintain moral values", "Show gratitude for food",
        "Help community", "Practice service (seva)", "Participate in spiritual talk", "Read spiritual book", "Practice breathing meditation",
        "Chant OM", "Reflect on kindness", "Avoid negative speech", "Appreciate nature", "Observe discipline",
        "Respect parents", "Respect teachers", "Seek wisdom", "Practice forgiveness", "Offer prayers before sleep",
        "Reflect on good deeds", "Practice gratitude journaling", "Practice calmness", "Avoid unnecessary complaints", "Appreciate simple living",
        "Observe self awareness", "Practice empathy", "Maintain inner peace", "Avoid hatred", "Promote harmony",
        "Share positivity", "Encourage good values", "Practice charity", "Respect traditions", "Learn spiritual philosophy",
        "Practice mindful breathing", "Reflect on impermanence", "Value relationships", "Avoid selfishness", "Cultivate compassion",
        "Practice discipline in prayer", "Reflect on life meaning", "Practice contentment", "Appreciate blessings", "Practice self reflection",
        "Observe silence moment", "Serve society", "Encourage peace", "Practice awareness", "Be thankful daily",
        "Maintain spiritual routine", "Practice kindness daily", "Reflect on moral actions", "Spread positivity", "Accept life calmly",
        "Maintain gratitude mindset", "Respect sacred spaces", "Promote good values", "Maintain inner discipline", "End day with gratitude"
    ]
};
